-- SELECT * FROM sakila.film;
-- 3) Select one column from a table. Get film titles
-- select distinct title from film;
-- 4) Select one column from a table and alias it. Get unique list of film languages under the alias language. 
-- select * from sakila.language;
-- select name as language 
-- from language;
-- 5-1) Find out how many stores does the company have?
-- select count(store_id) from store;
-- The company has two stores
-- 5-2) Find out how many employees staff does the company have?
-- select count(staff_id) from staff;
-- 5-3) Return a list of employee first names only?
select first_name from sakila.staff;